name: Build ESP32 CP2102 with PlatformIO

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: platformio run

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/esp32dev/firmware.bin
